"""Refactor Assessment to use a single QuestionBank

Revision ID: 0cf8b19b0687
Revises: d4baa2344961
Create Date: 2025-11-15 09:36:53.413497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0cf8b19b0687'
down_revision: Union[str, Sequence[str], None] = 'd4baa2344961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answer_logs', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'answer_logs', 'assessment_results', ['result_id'], ['id'])
    op.create_foreign_key(None, 'assessment_results', 'assessments', ['assessment_id'], ['id'])
    op.create_foreign_key(None, 'assessment_results', 'examinees', ['examinee_id'], ['id'])
    op.add_column('assessments', sa.Column('question_bank_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assessments', 'question_banks', ['question_bank_id'], ['id'])
    op.drop_column('assessments', 'question_bank_ids')
    op.drop_column('assessments', 'platform_id')
    op.create_foreign_key(None, 'options', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'procedures', 'question_banks', ['question_bank_id'], ['id'])
    op.create_foreign_key(None, 'question_banks', 'platforms', ['platform_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'procedures', ['procedure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'question_banks', type_='foreignkey')
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.add_column('assessments', sa.Column('platform_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('question_bank_ids', mysql.JSON(), nullable=False, comment='[1, 2, 5]'))
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'question_bank_id')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_constraint(None, 'answer_logs', type_='foreignkey')
    op.drop_constraint(None, 'answer_logs', type_='foreignkey')
    # ### end Alembic commands ###
