"""Add hashed_password to platforms table

Revision ID: 292ccdf23cf5
Revises: 1d888d89ab17
Create Date: 2025-11-22 06:06:41.416901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292ccdf23cf5'
down_revision: Union[str, Sequence[str], None] = '1d888d89ab17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answer_logs', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'answer_logs', 'assessment_results', ['result_id'], ['id'])
    op.create_foreign_key(None, 'assessment_results', 'examinees', ['examinee_id'], ['id'])
    op.create_foreign_key(None, 'assessment_results', 'assessments', ['assessment_id'], ['id'])
    op.create_foreign_key(None, 'assessments', 'question_banks', ['question_bank_id'], ['id'])
    op.create_foreign_key(None, 'options', 'questions', ['question_id'], ['id'])
    op.add_column('platforms', sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='平台密码的哈希值'))
    op.create_foreign_key(None, 'procedures', 'question_banks', ['question_bank_id'], ['id'])
    op.create_foreign_key(None, 'question_banks', 'platforms', ['platform_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'procedures', ['procedure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'question_banks', type_='foreignkey')
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_column('platforms', 'hashed_password')
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_constraint(None, 'answer_logs', type_='foreignkey')
    op.drop_constraint(None, 'answer_logs', type_='foreignkey')
    # ### end Alembic commands ###
