"""Add image_url to Question table

Revision ID: 4df8906d4d3e
Revises: 438229d5130e
Create Date: 2025-11-13 05:54:09.196426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df8906d4d3e'
down_revision: Union[str, Sequence[str], None] = '438229d5130e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answer_logs', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'answer_logs', 'assessment_results', ['result_id'], ['id'])
    op.create_foreign_key(None, 'assessment_results', 'examinees', ['examinee_id'], ['id'])
    op.create_foreign_key(None, 'assessment_results', 'assessments', ['assessment_id'], ['id'])
    op.create_foreign_key(None, 'assessments', 'platforms', ['platform_id'], ['id'])
    op.create_foreign_key(None, 'options', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'question_banks', 'platforms', ['platform_id'], ['id'])
    op.add_column('questions', sa.Column('image_url', sa.String(length=512), nullable=True, comment='题目关联的图片URL或路径'))
    op.create_foreign_key(None, 'questions', 'question_banks', ['question_bank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'image_url')
    op.drop_constraint(None, 'question_banks', type_='foreignkey')
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_constraint(None, 'answer_logs', type_='foreignkey')
    op.drop_constraint(None, 'answer_logs', type_='foreignkey')
    # ### end Alembic commands ###
