"""Relax constraints on scene_identifier in Question model

Revision ID: f426f9a9b265
Revises: 7400aa277202
Create Date: 2025-11-21 03:01:27.165663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f426f9a9b265'
down_revision: Union[str, Sequence[str], None] = '7400aa277202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answer_logs', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'answer_logs', 'assessment_results', ['result_id'], ['id'])
    op.create_foreign_key(None, 'assessment_results', 'assessments', ['assessment_id'], ['id'])
    op.create_foreign_key(None, 'assessment_results', 'examinees', ['examinee_id'], ['id'])
    op.create_foreign_key(None, 'assessments', 'question_banks', ['question_bank_id'], ['id'])
    op.create_foreign_key(None, 'options', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'procedures', 'question_banks', ['question_bank_id'], ['id'])
    op.create_foreign_key(None, 'question_banks', 'platforms', ['platform_id'], ['id'])
    op.alter_column('questions', 'question_type',
               existing_type=mysql.ENUM('DEDUCTION_SINGLE_CHOICE', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', charset='utf8mb4', collation='utf8mb4_unicode_520_ci'),
               type_=sa.Enum('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'DEDUCTION_SINGLE_CHOICE', name='questiontype'),
               existing_nullable=False)
    op.create_foreign_key(None, 'questions', 'procedures', ['procedure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.alter_column('questions', 'question_type',
               existing_type=sa.Enum('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'DEDUCTION_SINGLE_CHOICE', name='questiontype'),
               type_=mysql.ENUM('DEDUCTION_SINGLE_CHOICE', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', charset='utf8mb4', collation='utf8mb4_unicode_520_ci'),
               existing_nullable=False)
    op.drop_constraint(None, 'question_banks', type_='foreignkey')
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_constraint(None, 'answer_logs', type_='foreignkey')
    op.drop_constraint(None, 'answer_logs', type_='foreignkey')
    # ### end Alembic commands ###
